// <auto-generated />
using System;
using DBSqlLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBSqlLite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("DBSqlLite.SqlLiteModels.TaskSQLiteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFimTask")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioTask")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InsertID")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTask")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacaoTask")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Realizada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskSQLiteModel");
                });

            modelBuilder.Entity("DBSqlLite.SqlLiteModels.UsuarioSQLiteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IniciandoNoAplicativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsuarioSQLiteModel");
                });
#pragma warning restore 612, 618
        }
    }
}
